trigger:
  branches:
    include:
      - test

pool:
  name: laptop-agent

jobs:
  - job: SourceValidation
    displayName: 'Source Validation Job'
    steps:
      - checkout: self

      - script: |
          echo "Current Branch"
          echo "$(Build.SourceBranch)"
          if [ "$(Build.SourceBranch)" != "refs/heads/test" ]; then
              echo "Wrong branch"
              exit 1
          fi
          if [ ! -d "src" ]; then
              echo "src missing"
              exit 1
          fi
          echo "Source Validation Passed"
        displayName: 'Source Validation'

  - job: CodeQuality
    displayName: 'Code Quality & Testing Job'
    dependsOn: SourceValidation
    steps:
      - checkout: self

      - script: |
          echo "Checking tools"
          go version
          golangci-lint --version
        displayName: 'Verify Tools'

      - script: |
          cd src/frontend
          golangci-lint run > lint-report.txt || true
          cat lint-report.txt
          ISSUES=$(wc -l < lint-report.txt)
          echo "Issues found: $ISSUES"
        displayName: 'Run Lint'

      - script: |
          cd src/frontend
          go test ./...
        displayName: 'Run Unit Test'

      - script: |
          cd src/frontend
          go test -cover ./...
        displayName: 'Generate Coverage'

  - job: SAST
    displayName: 'Static Application Security Testing'
    dependsOn: CodeQuality
    steps:
      - checkout: self

      - task: SonarQubePrepare@8
        inputs:
          SonarQube: 'sonarqube-local'
          scannerMode: 'cli'
          configMode: 'manual'
          cliProjectKey: 'online-boutique'
          cliProjectName: 'online-boutique'
          cliSources: '.'
          extraProperties: |
            sonar.sources=src/frontend,src/checkoutservice,src/productcatalogservice,src/shippingservice

      - script: |
          echo "Starting SAST"
          cd src/frontend
          go test ./...
        displayName: 'Prepare Scan'

      - task: SonarQubeAnalyze@8

      - task: SonarQubePublish@8
        inputs:
          pollingTimeoutSec: '300'